### ISSUE TITLE
Wrong timestamp on videos

### ISSUE THREAD

**Issue by tomrtk** [tomrtk/fish-code#43]
Timestamp on videos is wrong for videos who is not 30min and using the serial number to calculate it.

Example:
![timestamp-bug](https://user-images.githubusercontent.com/43438127/124110537-9ec38600-da68-11eb-99fe-c5549a6e7dd4.png)

Reproduce by adding two videos not 30 min. long with same timestamp in filename and incremented serial number.

**Comment by MindTooth** [comment]
How can we approach this and provide a reliable way of calculating the correct timestamp?

**Comment by Kad1n** [comment]
It is possible to calculate the correct time based on the videos timestamp, frame count and framerate. In that case we could use the timestamp as just as a grouping of enumerations. The timestamp will also be used to hold start time for that batch of videos. Then we can use the enumeration after the videos to determine the order of videos with similar timestamp. Something like this:
`prefix[timestamp]-enumeration.mp4`
Video files with the same timestamp should be assumed to be continious, and have at least a few videos with enumeration. That way a job can consist of video files with different timestamps and enumerations, and still get correct output.
```
test[2021-01-01_00-00-00]-000.mp4
test[2021-01-01_00-00-00]-001.mp4
test[2021-01-01_00-00-00]-002.mp4
test[2021-07-20_00-00-00]-000.mp4
test[2023-11-22_00-00-00]-001.mp4
test[2023-11-22_00-00-00]-002.mp4
```

We could also add a field to a job named `start_timestamp` which stores the start timestamp for all the videos in that job. That way users dont require having a valid timestamp in their filename, its enough with just enumeration. However this means each job should only have videos for a single time period. 
`prefix-enumeration.mp4`
A jobs video files would look like this.
```
test-000.mp4
test-001.mp4
test-002.mp4
test-003.mp4
test-004.mp4
test-005.mp4
```

**Comment by R0flcopt3r** [comment]
This is rather awkward to solve. I did a quick test here, 203aa4cd7972d056fe6e412c287f4e6a02b2f0dc. It seems to work initially, haven't tested it thoroughly yet.

The initial implementation for timestamp parsing were done assuming all videos are 30 minutes long, which were how the customer did it. My current "hotfix" lets the videos be of any length, but requires that they are sorted, not sure if that is done? It's a small fix to add anyways.

**Comment by R0flcopt3r** [comment]
I've added functionality so that you can add clips with different timestamps, like so:
```
[2020-07-18_08-17-54]-000.mp4
[2020-07-18_08-17-54]-001.mp4
[2020-01-12_00-10-00]-000.mp4
[2020-01-12_00-10-00]-001.mp4
```
and the calculated timestamps are what you'd expect.

---

However, if I add `[2020-07-18_08-17-54]-003.mp4`, have to assume all clips before it is the same length as it. This might cause some issues if you add the last clip in a video and it is shorter than all the others.

This isn't a problem if you add a bunch of clips of varying length, given the first timestamp is calculated correctly.

**Comment by Kad1n** [comment]
Nice feature! Think it makes most sense to have numerated videos on the same date ignore the gap in time. User should get a warning if that occurs however. In order to detect objects in videos with as little error as possible, the video should always be contineous. Even if we have to "skip" the time for a video `[2020-07-18_08-17-54]-002.mp4` in the example you presented.
